name: New Issue Automation
on:
  issues:
    types:
      - opened
      - reopened
      - closed

jobs:
  issue_opened_and_reopened:
    name: issue_opened_and_reopened
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'opened' || github.event.action == 'reopened'
    steps:
      - name: 'Discord notification'
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_GITHUB_NOTIFICATIONS_CHANNEL_WEBHOOK }}
          DISCORD_EMBEDS: '[{"color":3447003,"title":"${{ github.event.issue.title}} #${{github.event.issue.number}}","url":"${{ github.event.issue.html_url }}","author":{"name":"${{ github.event.issue.user.login }}","icon_url":"${{ github.event.issue.user.avatar_url }}","url":"${{ github.event.issue.user.html_url }}"},"description":"Issue - ${{ github.event.action }}"}]'
